import { useState } from 'react';
import { BatteryCharging, KeyRound, LoaderCircle, ShieldCheck } from 'lucide-react';
import { login, setToken } from '../lib/api';

export default function Login({ onLogin }) {
  const [mode, setMode] = useState('credentials'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { if (mode === 'token') setToken(values.token.trim()); else await login(values.mobile, values.password); onLogin(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <main className="login-page"><section className="login-brand-panel"><div className="login-logo"><BatteryCharging /><span>MOVAN</span></div><div className="login-message"><p>BATTERY OPERATIONS / ONE VIEW</p><h1>Control the full service journey.</h1><span>Customers. Warranty. Inventory. Decisions.</span></div><div className="login-proof"><ShieldCheck /><div><strong>Administrative access</strong><span>Protected by role permissions and an audit trail.</span></div></div></section><section className="login-form-panel"><div className="login-card"><p className="eyebrow">Movan control desk</p><h2>Welcome back</h2><p>Sign in to manage today’s operations.</p><div className="login-tabs"><button className={mode === 'credentials' ? 'active' : ''} onClick={() => setMode('credentials')}>Password</button><button className={mode === 'token' ? 'active' : ''} onClick={() => setMode('token')}>Access token</button></div><form onSubmit={submit}>{mode === 'credentials' ? <><label><span>Mobile number</span><input name="mobile" type="tel" placeholder="Admin mobile number" required /></label><label><span>Password</span><input name="password" type="password" placeholder="Enter password" required /></label></> : <label><span>Bearer token</span><textarea name="token" rows="5" placeholder="Paste a valid admin access token" required /></label>}{error && <div className="inline-error">{error}</div>}<button className="button button-primary button-full" disabled={busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <KeyRound size={18} />}{busy ? 'Authenticating...' : 'Enter control desk'}</button></form><small>Only authorized Movan personnel may continue.</small></div></section></main>;
}
