import { useEffect, useState } from 'react';
import { Download, FileBarChart2, RefreshCw } from 'lucide-react';
import { api, BASE_URL, getToken } from '../lib/api';
import { ErrorState, LoadingState } from '../components/DataState';

const reportMap = { sales: '/business/reports/sales', stock: '/business/reports/stock', expenses: '/business/reports/expenses', dealers: '/business/reports/dealer-sales' };

export default function Reports() {
  const [tab, setTab] = useState('sales'); const [data, setData] = useState(null); const [error, setError] = useState(null);
  const load = async () => { setData(null); try { const payload = await api(reportMap[tab]); setData(payload.data || []); setError(null); } catch (err) { setError(err); } };
  useEffect(() => { load(); }, [tab]);
  const exportReport = async (kind) => { const response = await fetch(`${BASE_URL}/reports/export/${kind}`, { headers: { Authorization: `Bearer ${getToken()}` } }); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `movan-${kind}-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Decision support</p><h1>Business Reports</h1><p>Live operational and commercial reporting.</p></div><div className="heading-actions"><button className="button button-secondary" onClick={() => exportReport('customers')}><Download size={16} /> Customers</button><button className="button button-primary" onClick={() => exportReport('service-cases')}><Download size={16} /> Service cases</button></div></div><section className="card report-shell"><div className="report-tabs">{Object.keys(reportMap).map((item) => <button className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div><div className="report-title"><div><FileBarChart2 /><div><h2>{tab[0].toUpperCase() + tab.slice(1)} report</h2><p>Generated from the current API dataset</p></div></div><button className="icon-button" onClick={load}><RefreshCw size={18} /></button></div>{!data && !error ? <LoadingState /> : error ? <ErrorState error={error} onRetry={load} /> : <div className="table-scroll"><table><thead><tr><th>Record</th><th>Details</th><th>Value</th><th>Date / status</th></tr></thead><tbody>{data.map((item, index) => <tr key={item._id || index}><td><strong>{item.productName || item.invoiceNumber || item.category || item._id || `Record ${index + 1}`}</strong><small>{item.productCode || item.paymentMethod}</small></td><td>{item.customerId?.name || item.brand || item.description || `${item.count || item.items?.length || 0} item(s)`}</td><td><strong>{item.totalAmount ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(item.totalAmount) : item.currentStock ?? item.amount ?? '-'}</strong></td><td>{item.saleDate ? new Date(item.saleDate).toLocaleDateString('en-IN') : item.paymentStatus || item.category || '-'}</td></tr>)}{!data.length && <tr><td colSpan="4"><div className="state-panel"><strong>No report records for this period</strong></div></td></tr>}</tbody></table></div>}</section></div>;
}

