import { useEffect, useState } from 'react';
import { BellRing, CheckCircle2, DatabaseBackup, Play, RefreshCw, Server, ShieldCheck } from 'lucide-react';
import { api } from '../lib/api';
import { ErrorState, LoadingState } from '../components/DataState';

export default function SystemCenter() {
  const [data, setData] = useState(null); const [error, setError] = useState(null); const [running, setRunning] = useState(false); const [notice, setNotice] = useState('');
  const load = async () => { try { const [health, version, backup, history, permissions, notifications] = await Promise.all([api('/system/health'), api('/system/version'), api('/backup/status'), api('/backup/history'), api('/auth/permissions'), api('/notifications')]); setData({ health: health.data, version: version.data, backup: backup.data, history: history.data || [], permissions: permissions.data, notifications: notifications.data || [] }); setError(null); } catch (err) { setError(err); } };
  useEffect(() => { load(); }, []);
  const runBackup = async () => { setRunning(true); try { await api('/backup/run', { method: 'POST' }); setNotice('Backup job started successfully.'); await load(); } catch (err) { setNotice(err.message); } finally { setRunning(false); } };
  if (!data && !error) return <LoadingState label="Checking system health" />;
  if (error) return <ErrorState error={error} onRetry={load} />;
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Platform governance</p><h1>System Center</h1><p>Health, permissions, backups, and administrative signals.</p></div><button className="button button-secondary" onClick={load}><RefreshCw size={16} /> Recheck</button></div>{notice && <div className="notice"><span>{notice}</span><button onClick={() => setNotice('')}>Dismiss</button></div>}<div className="system-grid"><article className="card system-card"><div className="system-card-head"><Server /><span className="status-pill status-positive">Operational</span></div><h2>API service</h2><p>{data.health?.status || data.health?.message || 'All health checks passed'}</p><dl><div><dt>Version</dt><dd>{data.version?.version || data.version?.apiVersion || 'v1'}</dd></div><div><dt>Environment</dt><dd>{data.version?.environment || 'production'}</dd></div></dl></article><article className="card system-card"><div className="system-card-head"><DatabaseBackup /><span className="status-pill status-positive">{data.backup?.status || 'Ready'}</span></div><h2>Data backup</h2><p>Run an authenticated snapshot of the current platform data.</p><button className="button button-primary button-full" disabled={running} onClick={runBackup}><Play size={16} /> {running ? 'Starting...' : 'Run backup now'}</button></article><article className="card system-card"><div className="system-card-head"><ShieldCheck /><span>{Array.isArray(data.permissions) ? data.permissions.length : Object.keys(data.permissions || {}).length}</span></div><h2>Admin permissions</h2><p>Your current token has active platform control permissions.</p><div className="permission-preview">{(Array.isArray(data.permissions) ? data.permissions : Object.keys(data.permissions || {})).slice(0, 5).map((permission) => <span key={permission}><CheckCircle2 size={13} /> {permission}</span>)}</div></article><article className="card system-card"><div className="system-card-head"><BellRing /><span>{data.notifications.length}</span></div><h2>Notifications</h2><p>{data.notifications.length ? 'Unread operational notifications require review.' : 'No notifications are waiting for review.'}</p></article></div><section className="card table-card"><div className="table-toolbar"><div><p className="eyebrow">Recovery trail</p><h2>Backup history</h2></div></div><div className="table-scroll"><table><thead><tr><th>Started</th><th>Status</th><th>Type</th><th>Location / message</th></tr></thead><tbody>{data.history.map((item) => <tr key={item._id}><td>{new Date(item.createdAt || item.startedAt).toLocaleString('en-IN')}</td><td><span className={`status-pill status-${item.status}`}>{item.status}</span></td><td>{item.type || 'Full backup'}</td><td>{item.location || item.message || '-'}</td></tr>)}</tbody></table></div></section></div>;
}

