import { useEffect, useState } from 'react';
import { NavLink, useLocation, useNavigate } from 'react-router-dom';
import { Activity, BatteryCharging, Bell, BookOpenCheck, Boxes, ChevronRight, CircleDollarSign, FileBarChart2, Gauge, LifeBuoy, LogOut, Menu, Package, Search, Settings, ShieldCheck, ShoppingCart, Store, Truck, Users, WalletCards, Wrench, X } from 'lucide-react';
import { api, setToken } from '../lib/api';

const groups = [
  { label: 'Overview', items: [{ to: '/', label: 'Dashboard', icon: Gauge }] },
  { label: 'Operations', items: [{ to: '/service-cases', label: 'Service cases', icon: Wrench }, { to: '/customers', label: 'Customers', icon: Users }, { to: '/batteries', label: 'Battery registry', icon: BatteryCharging }, { to: '/loaners', label: 'Loaner fleet', icon: LifeBuoy }, { to: '/battery-finder', label: 'Battery finder', icon: Search }] },
  { label: 'Business', items: [{ to: '/products', label: 'Products', icon: Package }, { to: '/stock', label: 'Stock control', icon: Boxes }, { to: '/dealers', label: 'Dealers', icon: Truck }, { to: '/purchases', label: 'Purchases', icon: ShoppingCart }, { to: '/sales', label: 'Sales', icon: CircleDollarSign }, { to: '/expenses', label: 'Expenses', icon: WalletCards }, { to: '/reports', label: 'Reports', icon: FileBarChart2 }] },
  { label: 'Administration', items: [{ to: '/users', label: 'Users & staff', icon: ShieldCheck }, { to: '/roles', label: 'Roles', icon: ShieldCheck }, { to: '/shops', label: 'Shops', icon: Store }, { to: '/alert-rules', label: 'Alert rules', icon: Bell }, { to: '/templates', label: 'Message templates', icon: BookOpenCheck }, { to: '/audit', label: 'Audit log', icon: Activity }, { to: '/system', label: 'System center', icon: Settings }] },
];

export default function Layout({ children, onLogout }) {
  const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); const [profile, setProfile] = useState(null); const location = useLocation(); const navigate = useNavigate();
  useEffect(() => { api('/auth/me').then((result) => setProfile(result.data)).catch(() => {}); }, []);
  useEffect(() => { setMobileOpen(false); }, [location.pathname]);
  const logout = () => { setToken(''); onLogout(); };
  const search = (event) => { event.preventDefault(); const query = new FormData(event.currentTarget).get('query')?.trim(); if (query) navigate(`/search?q=${encodeURIComponent(query)}`); };
  return <div className={`app-shell ${collapsed ? 'sidebar-collapsed' : ''}`}><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><BatteryCharging /></div><div><strong>MOVAN</strong><span>CONTROL</span></div><button className="mobile-close" onClick={() => setMobileOpen(false)}><X /></button></div><nav>{groups.map((group) => <div className="nav-group" key={group.label}><p>{group.label}</p>{group.items.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} title={label}><Icon size={18} /><span>{label}</span><ChevronRight className="nav-chevron" size={13} /></NavLink>)}</div>)}</nav><div className="sidebar-foot"><div className="sidebar-help"><BookOpenCheck /><div><strong>API connected</strong><span>Production · v1</span></div></div><button onClick={logout}><LogOut size={17} /><span>Sign out</span></button></div></aside>{mobileOpen && <button className="sidebar-scrim" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}<div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="menu-button desktop-menu" onClick={() => setCollapsed(!collapsed)}><Menu /></button><button className="menu-button mobile-menu" onClick={() => setMobileOpen(true)}><Menu /></button><form className="global-search" onSubmit={search}><Search size={17} /><input name="query" aria-label="Global search" placeholder="Search customers, serials, vehicles..." /></form></div><div className="topbar-right"><button className="notification-button" aria-label="Open notifications" onClick={() => navigate('/notifications')}><Bell size={19} /><i /></button><div className="admin-profile"><div className="avatar">{profile?.name?.slice(0, 2).toUpperCase() || 'AD'}</div><div><strong>{profile?.name || 'Administrator'}</strong><span>{profile?.role || 'Admin'}</span></div></div></div></header><main className="content">{children}</main><footer className="app-footer"><span>Movan Batteries Administration</span><span>Secure API session</span></footer></div></div>;
}
